### PR TITLE
Proposed fix for #55

### PR DESCRIPTION
**Pull request by zediah**
Fix issues as in issue #55 

The only caveat is that I was unable to work out a way to maintain the same function ref when the child.ref is set. At the moment it'll just do it the usual way...

This fixes my situation as I don't often have ref's on the child (always wrapped).

### CODE REVIEW

**Comment by jquense** [comment]
Hi there, thanks a lot for the PR. I'll admit that I'm not the most familar with the logic react uses here, but this feels "hacky" to me, I'd expect that regardless of the function identity the ref should be called with the instance (after being `null`ed out) not just broken as in our case...

@gaearon do you have any insight on this? I realize that refs are called with `null` but if the ref function changes should it go `inst -> null -> inst` again?

**Comment by gaearon** [comment]
>but if the ref function changes should it go inst -> null -> inst again?

Yes, it's expected to first give you `null` before the update, and then give you the `inst` again after the update. So I think the right fix would be to ensure that any user-specified callbacks run after the DOM is flushed and refs are ready.

**Comment by jquense** [comment]
Is that feasible with the public API? I can imagine wrapping callbacks in like a `forceUpdate(callback)` but that seems iffy? In the past i would just require '`lib/ReactUpdates.asap` directly ;)

**Comment by gaearon** [comment]
Hmm. I don't remember how TransitionGroup works, but are `componentDidMount` and `componentDidUpdate` hooks not sufficient? They fire after refs are attached.

**Comment by zediah** [comment]
My approach to this problem was that, it worked before because the refs stayed the same - so I'd replicate that. If there's a better way, I'm definitely up for it!

I agree with you having to store the function for each key seems a bit hacky, but I'd argue that this is a result of a different 'accepted' pattern now being used for refs. Previously you'd have a single string, that didn't change unless well...it did change. Now the 'pattern' is to declare an anonymous function each time - thus making it a 'new' ref, making react detach/reattach each time. Is there an advantage to this I'm not aware of? Was it a conscious decision to make this the new norm?

To me it seems a bit of an anti pattern as it'll make react do (a little bit) more work than is required and as shown here - the ref isn't available when it's expected to be. I'd also argue that the ref function in 99% of cases wouldn't change, so why are we re-creating it? (these are genuine question, I'm curious!)

@gaearon Would that mean to suggest deferring the callback call until componentDidUpdate in either the library code or my code? (or both?)

**Comment by jquense** [comment]
should be fixed by #72

**Pull request closed without merging**
