### PR TITLE
Bundle UMD with rollup

### PR DESCRIPTION
**Pull request by TrySound**
```diff
-Webpack production bundle is 18407b (no gzip)
+Rollup production bundle is 14975b (no gzip)
```

### CODE REVIEW

**Comment by TrySound** [comment]
Oops, it's 14975b. Didn't expected such behaviour from babel config. I don't like custom presets for this. They need to be learned.

**Comment by TrySound** [comment]
Guys, I already have esm support locally. Will push it after merging this PR.

**Comment by TrySound** [comment]
Hi @silvenon. Could you take a look at this?

**Comment by TrySound** [comment]
@silvenon Friendly ping

**Comment by TrySound** [comment]
Sorry for noise. Just want to get things done :)
/cc @silvenon

**Comment by TrySound** [comment]
@silvenon Ping :)

**Comment by jquense** [comment]
I think we can move this along, happy to any  feedback in retro

**Comment by silvenon** [comment]
So sorry guys, I got swamped up in notifications and just recently said YOLO and marked them all as read. Thanks a lot @TrySound for your work, thanks @jquense for reviewing ❤️

**Pull request merged**
