### PR TITLE
Strip custom prop-types in production

### PR DESCRIPTION
**Pull request by TrySound**
Minified size with bundled dependencies before
17.53 KB
After
16.66 KB

### CODE REVIEW

**Comment by TrySound** [comment]
Yep

**Comment by TrySound** [comment]
@jquense Is this good now?

**Comment by oliviertassinari** [comment]
-200 B gzipped https://bundlephobia.com/result?p=react-transition-group@2.5.3 🚀

**Comment by jquense** [comment]
hmm we are still including the prop-types library tho. seems like the import isn't getting stripped

**Comment by oliviertassinari** [comment]
@jquense It's not. I wish the babel plugin was doing such.

**Comment by oliviertassinari** [comment]
It's another gain potential. https://bundlephobia.com/result?p=prop-types@15.6.2. However, I'm not sure how we can make it work with ESM modules. Conditionally importing modules? I doubt we can 🤔.

**Comment by TrySound** [comment]
It's because of old context api I guess

**Pull request merged**
