### PR TITLE
feat: add SwitchTransition component

### PR DESCRIPTION
**Pull request by dimensi**
Hi @jquense and @silvenon, I came from vue and when I didn’t find the transition modes for the transition component, I started biting my elbows and worked with animations using `position: absolute`. I put together a fist and wrote a component that adds transition modes.
I saw [this](https://github.com/reactjs/react-transition-group/issues/339) and that the @jquense wants to [add it](https://github.com/reactjs/react-transition-group/issues/339#issuecomment-390315102). But the idea of the @jquense is that you need to pump through exactly the same component, I was not understood.
Here is a live example of this component https://codesandbox.io/s/50p5wr3jwl.
My idea is that I essentially repeat the behavior of the vue transition. If you change the key, the animation will play, if you change the components, but do not touch the keys, the component will be updated, but the animation will not play.
I have not added tests or jsdoc yet, because I want to get feedback first.

### CODE REVIEW

**Comment by dimensi** [comment]
@jquense, @silvenon  ?

**Comment by jquense** [comment]
Hi @dimensi this looks great! sorry for the delay folks are working on stuff in their spare time and we're all a bit busy right now, so sorry for the long gap. Hoping i can give this a proper review soon. thanks a ton for doing this!

**Comment by dimensi** [comment]
Sorry, @jquense, i really want release this feature.

**Comment by jquense** [comment]
Looks good @dimensi can you add some tests and documentation?

**Comment by dimensi** [comment]
@jquense, I've added documentation and tests

**Comment by dimensi** [comment]
@jquense, i update switch for context api, but now can't create sandbox with new version, because transitiongroup context now not exported.

**Comment by jquense** [comment]
@dimensi you should be able to cherry pick it `import TransitionGroupContext from 'react-transition-group/TransitionGroupContext'`

**Comment by dimensi** [comment]
image
codesandbox not see /esm or cjs forders

**Comment by jquense** [comment]
thanks! sorry for the long delay :\

**Comment by dimensi** [comment]
I leave here working example: https://codesandbox.io/s/50p5wr3jwl

**Pull request merged**
