### PR TITLE
fixed ios 8.0 not have Object.assign

### PR DESCRIPTION
**Pull request by GoToBoy**
add a _.extend to fixed when was in ios 8.0

### CODE REVIEW

**Comment by oliviertassinari** [comment]
💯  for fixing that issue. It's also breaking support with IE11. React used to take care of that issue. For instance here is the output of `react/lib/ReactTransitionGroup`:
```js
'use strict';

var _assign = require('object-assign');

// ...

var props = _assign({}, this.props);
```

**Comment by oliviertassinari** [comment]
@GoToBoy What about using `https://www.npmjs.com/package/babel-plugin-transform-object-assign` instead?

**Comment by oliviertassinari** [comment]
@jquense I think that you want to have a look at it as a regression with the deprecated https://www.npmjs.com/package/react-addons-transition-group package.

**Comment by jquense** [comment]
Thanks y'all, yes we want to fix this but not with a self included polyfill. Let's use the Babel plugin that handles this automatically thanks!

**Comment by jquense** [comment]
And sorry for the oversight!

**Comment by kenfehling** [comment]
Also came across this issue. As per @oliviertassinari's suggestion, I've opened a pull request using babel-plugin-transform-object-assign: https://github.com/reactjs/react-transition-group/pull/35

**Pull request closed without merging**
