### PR TITLE
Support esm via package.json routes

### PR DESCRIPTION
**Pull request by TrySound**
Ref #77

Upgraded semantic-release-alt-publish-dir to get correct module field
processing

https://github.com/jquense/semantic-release-alt-publish-dir/commit/795af9dae9a30d06268ac64a15e5072ea8d73906

### CODE REVIEW

**Comment by TrySound** [comment]
Same PR as previously but with fixed module field
/cc @jquense @silvenon

**Comment by taion** [comment]
same as https://github.com/reactjs/react-transition-group/pull/455

this is fine; we'll need to note the breaking change for semver

**Comment by jquense** [comment]
what is the breaking change again?

**Comment by TrySound** [comment]
Here's a breaking change
https://github.com/reactjs/react-transition-group/issues/475

**Comment by taion** [comment]
@jquense it's https://github.com/reactjs/react-transition-group/issues/475#issuecomment-475782739

if you have a CJS module that imports the ESM build due to the inter-op, then you will actually get the ESM module this time around, which means you'll need to add the `.default`

**Pull request merged**
