### PR TITLE
fix(CSSTransition): done classname for appearing

### LINKED ISSUE #327: done classname for appearing
**Do you want to request a *feature* or report a *bug*?**

bug?

**What is the current behavior?**

```
    <CSSTransition in appear timeout={timeout} classNames="fade">
        {props.children}
    </CSSTransition>
```

The above case, CSSTransition applies the following classNames in the order.

* `.fade-appear`
* `.fade-appear.fade-appear-active`
* `.fade-enter-done`

Is adding `.fade-enter-done` classname to a component an expected behavior?
I think it would be better the classname will be `.fade-appear-done` instead of `.fade-enter-done`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

https://codesandbox.io/s/7w59nmnn1x

**What is the expected behavior?**

A component is added `.fade-appear-done` instead of `.fade-enter-done`.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

### PR DESCRIPTION
**Pull request by koba04**
Fix #327

### CODE REVIEW

**Comment by silvenon** [comment]
Thanks for this! There's a discussion in #327 about which classes to apply exactly, feel free to join in.

**Comment by koba04** [comment]
Thanks!

**Comment by silvenon** [comment]
@koba04 thanks for suggesting the change and the PR. 😉

**Pull request closed without merging**
