### PR TITLE
Fix TransitionGroup error on quick toggle of components

### PR DESCRIPTION
**Pull request by scyrizales**
I had this pull request to address this issue: https://github.com/reactjs/react-transition-group/issues/12

### CODE REVIEW

**Comment by xStrom** [comment]
How sure are we that returning is the correct behavior? By just immediately returning `currentlyTransitioningKeys` will remain inconsistent.

Previous attempts ([#6710](https://github.com/facebook/react/pull/6710), [#6745](https://github.com/facebook/react/pull/6745)) only guarded execution of code that directly depends on `component` being defined, but still executed the other parts of the function like `currentlyTransitioningKeys` cleanup.

Unless there's a good case for immediately returning, I think just guarding the `component` usage is a better solution.

**Comment by jquense** [comment]
I agree with @xStrom, we shouln't return early here, but guard the actual callback so the rest of the state can be properly cleaned up

**Comment by scyrizales** [comment]
@xStrom I have just updated the PR

**Comment by xStrom** [comment]
Looks good, I think we should merge this.

**Pull request merged**
