### PR TITLE
CSSTransition: don't reflow when there's no class to add

### PR DESCRIPTION
**Pull request by michaelkix**

### CODE REVIEW

**Comment by silvenon** [comment]
CI is failing because the commit message doesn't adhere to the preferred format; to make this easier for contributors, I pushed some changes to `master` branch which will install a git hook and lint messages of your subsequent commits.

To lint the message of your last commit run `npx commitlint -e`. To see more options run `npx commitlint --help`.

**Comment by silvenon** [comment]
I. e. we'll merge as soon as you edit the commit message (you can amend and force push). Initially I was thinking about adding a test for this, but I don't think jsdom "knows" about reflows. 😄

**Comment by silvenon** [comment]
I edited the commit message and merged in b5cc923dfd3f6339a9cce52767f1f6922cb2da66. Thanks!

**Comment by jquense** [comment]
@silvenon in the future you can pick `squash and merge` from the merge menu here and it will give you a chance to set the commit message for the squashed commit

**Comment by silvenon** [comment]
Noted! @michaelkix sorry about that, I hope that the fact that you are the author of that commit shows up in your contribution graph. 😃

**Pull request closed without merging**
