### PR TITLE
chore: Bump deps

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
d'oh

**Comment by taion** [comment]
@silvenon okay, the storybook was screwed up more broadly because the transitions themselves were disabled. i fixed it and modernized some of the code. i also took out those 2 stale test cases

**Comment by iamandrewluca** [comment]
My suggestion would be to revert back `react` and `react-dom` `devdependencies` versions to

```
"react": "~16.6.3",
"react-dom": "~16.6.3",
```

because they are listed also in `peerDependencies`, and there is a risk to use some `react` APIs that are not supported by the dependencies of `react-transition-group` users

**Comment by taion** [comment]
The peer dependencies use a `>=` range. I expect most users are actually on the latest React versions at this point, so it seems to me to make more sense to test against those.

**Comment by iamandrewluca** [comment]
> I expect most users are actually on the latest React versions at this point

I also thought this on `redux-form` but it seems is not the case.

What I mean above is that for example I'm working on a feature `react-transition-group` and I will be tempted to use a react feature that was introduced in react `>16.8`. And we release this new feature. And some users of the library, may still have react `16.6` installed, and their build will fail.

**Comment by silvenon** [comment]
I think it's best to set up a sanity test on CI with lowest supported React version.

**Pull request merged**
