### PR TITLE
chore: fix Gatsby build

### PR DESCRIPTION
**Pull request by silvenon**
This is a mix of updates, sorry about that, I couldn't really narrow down why Gatsby was failing for me (I don't know if anyone else was experiencing this), it seems to have been a combination of issues which were taking too long to isolate. Anyway, now our Gatsby dependencies are out of beta and we're using official Gatsby Babel preset, so things should be more stable in the future.

Also, I migrated to latest react-bootstrap, very easy migration so 👍 to the team 😉

Can't wait to start upgrading docs with better examples after this…

### CODE REVIEW

**Comment by silvenon** [comment]
Since this is just a change to building the docs, I'll go ahead and merge this.

**Comment by dimensi** [comment]
@silvenon what's happen with documentations on https://reactcommunity.org/react-transition-group/ ? It is not updated after releases, is it because skip ci?

**Comment by silvenon** [comment]
@dimensi good question. I think it needs to be deployed manually with the current setup, I'm looking into it and will deploy it one way or another 😉 

But I still want to brush up the docs content before deploying. Feel free to suggest any additions. 😉

**Pull request merged**
